import type { CSSProperties } from 'react'

/**
 * Native <picture> serving pre-built AVIF + WebP variants.
 *
 * Sources live in /public/images/opt/, generated by scripts/optimize-images.mjs
 * in two sizes (md=960w, lg=1920w). The browser negotiates format & size at
 * request time — no Vercel image optimizer involved, which keeps cold-cache
 * loads instant.
 *
 * Usage:
 *   <Picture src="igb-3" alt="..." width={1920} height={1440} priority />
 *   <Picture src="igb-3" alt="..." fill sizes="100vw" />
 *
 * To add a new image: drop the source into /public/images/ and run
 *   npm run optimize:images
 */

type Props = {
  /** Base filename (no extension, no path). Example: "igb-3". */
  src: string
  alt: string
  /** Required when `fill` is false — used to reserve layout and avoid CLS. */
  width?: number
  height?: number
  className?: string
  /** Responsive `sizes` attribute. Default: "100vw". */
  sizes?: string
  /** Absolute-positioned to fill the nearest positioned parent. */
  fill?: boolean
  /** Mark as the LCP element: eager + fetchpriority=high + sync decode. */
  priority?: boolean
  /** Override loading when not priority (default: lazy). */
  loading?: 'eager' | 'lazy'
  style?: CSSProperties
}

const OPT_DIR = '/images/opt'
const VARIANTS = [
  { key: 'md', w: 960 },
  { key: 'lg', w: 1920 },
] as const

/** Accept either "igb-3" or "/images/igb-3.webp" — strip dir + extension. */
function normalize(name: string) {
  return name.replace(/^.*\//, '').replace(/\.[^.]+$/, '')
}

function buildSrcSet(name: string, ext: 'avif' | 'webp') {
  return VARIANTS.map((v) => `${OPT_DIR}/${name}-${v.key}.${ext} ${v.w}w`).join(', ')
}

export default function Picture({
  src,
  alt,
  width,
  height,
  className,
  sizes = '100vw',
  fill = false,
  priority = false,
  loading,
  style,
}: Props) {
  const name = normalize(src)
  const fallbackSrc = `${OPT_DIR}/${name}-lg.webp`
  const effectiveLoading = priority ? 'eager' : loading ?? 'lazy'

  const imgClass = fill
    ? `absolute inset-0 w-full h-full ${className ?? ''}`.trim()
    : className

  // React expects camelCase `fetchPriority`; it renders as lowercase in the DOM.
  // Spread via an untyped object so older @types/react versions don't warn.
  const priorityProps = priority
    ? ({ fetchPriority: 'high' } as Record<string, string>)
    : {}

  return (
    <picture>
      <source type="image/avif" srcSet={buildSrcSet(name, 'avif')} sizes={sizes} />
      <source type="image/webp" srcSet={buildSrcSet(name, 'webp')} sizes={sizes} />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={fallbackSrc}
        alt={alt}
        width={fill ? undefined : width}
        height={fill ? undefined : height}
        loading={effectiveLoading}
        decoding={priority ? 'sync' : 'async'}
        sizes={sizes}
        className={imgClass}
        style={style}
        {...priorityProps}
      />
    </picture>
  )
}
